spring:
  config:
    import: optional:secret.properties
  datasource:
    url: jdbc:postgresql://localhost:5432/buyleaf
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

aws:
  region: ap-south-1
#  credentials:
#    access-key:
#    secret-key:
